language: python
python:
  - '2.7'
  - '3.0'
  - '3.1'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
sudo: false 
env:
  global:
    - FOO="BAR"
install:
  - pip install -U pip
  - pip install -i $PYPI .
script:
  - nosetests --stop --verbose tests

